### ISSUE TITLE
Ctrl+Shift+M (the new "move" shortcut) repeats the last copy. The legacy shortcut Shift+M still works.

### ISSUE THREAD

**Issue by Betterbird** [kewisch/quickmove-extension#88] opened 2023-07-08 12:07 UTC
Observed on Windows.

On Windows, certain key combinations are already used, see:
Message menu:
![image](https://github.com/kewisch/quickmove-extension/assets/86832723/453c07f6-7acd-4454-a092-860ccfc7cdfb)

Ctrl+Shift+G brings up the "Find" box in the message preview, not sure where this is defined.

Ctrl+Shift+C works.

**Comment by xyxzxyz** [comment] 2023-07-14 18:35
None of the new shortcut keys works in my TB 115, legacy shortcuts still works tho.

**Comment by sluedecke** [comment] 2023-07-18 05:38
Same on Linux, no shortcut works at all, not even legacy.  TB 115

**Comment by pspacek** [comment] 2023-07-24 14:35
I confirm that the new shotcuts do not work for me on Thunderbird 115.0.1 on Arch linux. Legacy shortcuts do work fine after activation in addon preferences.

**Comment by kewisch** [comment] 2023-08-19 19:00
Ugh yes, I see. I had been developing on mac where it uses MacCtrl. I'm not sure I can do much aside from using a completely different shortcut on windows and linux. What do you think it should be? Needs to be one that can be set in the shortcut manager.

In the meanwhile, as noted, you can use legacy shortcuts as noted or pick one in the shortcuts manager.

**Comment by kewisch** [comment] 2023-08-21 19:24
Are these free on Windows?

Alt+Shift+M / Alt+Shift+C / Alt+Shift+G / Alt+Shift+T

**Comment by Cito** [comment] 2023-08-21 19:37
> Are these free on Windows?
> Alt+Shift+M / Alt+Shift+C / Alt+Shift+G / Alt+Shift+T

No, only Alt-Shift-C. The others the menus "Message", "Go" and "Tools". At least in English. Other languages may use different Alt+Shift combinations because the latters are taken from the menu titles.

**Comment by kewisch** [comment] 2023-08-21 19:44
Yeah, I'll have to target English only for the moment, though I could make those keyboard shortcuts localizable I think. Can you try around a few other combinations to see if there is anything left that would work? Shortcuts are scarce unfortunately, hope we can find something that is at least consistent in modifiers.

**Comment by Cito** [comment] 2023-08-21 19:52
The used keys with Alt+Shift are: D = Dark Reader Add-On, E = Edit Menu, F = File Menu, G = Go Menu, H = Help Menu, M = Message Menu, N = Events Menu, T = Tools Menu, V = View Menu. All others seem to be free.

**Comment by kewisch** [comment] 2023-08-21 20:06
What about combinations with Ctrl+Shift, or Ctrl+Alt?

**Comment by Cito** [comment] 2023-08-21 20:55
The used keys with Ctrl+Shift are: A = Select Thread, B = Adress Book,  F = Search Messages, G = Find in Page, I = Dev Tools, K = Quick Filter, L = Reply List, M = Move/Copy message to previous target, O = Open,  R = Reply, T = Reopen Tab.

**Comment by Cito** [comment] 2023-08-21 21:13
Ctrl-Alt does not seem to be used on Windows for Thunderbird.

**Comment by Betterbird** [comment] 2023-08-21 21:33
Ctrl+Alt equates to AltGr on Windows (https://en.wikipedia.org/wiki/AltGr_key), and AltGr+<something> is used frequently. So some clashes are preprogrammed, For example, AltGr is used on Polish keyboards to access accented characters. That said, you could try AltGr+M/C/G.

**Comment by Cito** [comment] 2023-08-22 04:51
> Ctrl+Alt equates to AltGr on Windows

"Because of this feature, Microsoft advises that Ctrl+Alt not be used as part of any application keyboard shortcut, as it would prevent typing the matching AltGr character on such keyboards."

Ctrl+Alt is also often used as global keyboard shortcut to start certain programs, like Ctrl+Alt+G = Search on Google Drive, Ctrl+Alt+K = KeePass or Kindle PC, Ctrl+Alt+A = Global Autotype in KeePass etc.

**Comment by kewisch** [comment] 2023-08-22 20:32
So maybe Ctrl+Alt, and then if folks have these set to something else (accent or global shortcut), they can change it in the shortcut manager?

**Comment by r7nuk** [comment] 2023-08-24 20:54
I've defined the following shortcuts under Manage Extension Shortcuts:
- Move selected messages = Ctrl+Shift+V _(i.e. mo**V**e)_
- Copy selected messages = Ctrl+Shift+P _(i.e. co**P**y)_
- Go to folder = Ctrl+Shift+Period _(i.e. the full stop because on my keyboard it also has the "**>**" symbol which I mentally link to "go to")_

I'm on Linux (Solus) using Thunderbird 115.1.1.

**Comment by KC-T** [comment] 2023-09-16 04:58
Version 2.0.1 on Thunderbird 115.2.2 on Windows 11.

Ctrl+Shift+M or Y or G behave like the previous version of repeating the previous action. The previous Shift+M or Y or G to specify new choices can only be done using the menu button instead of keyboard shortcuts. This would slow down the move. In case of limited choices, I would prefer using Ctrl-Shift+M or Y or G to bring up the new choice windows, which could include the last choice on the first row followed by other newly selected choices.

**Comment by unode** [comment] 2023-09-19 09:31
Is there any way to make the shortcuts configurable?

It sounds like clashes on different systems will be unavoidable.
Some Desktop/Window managers also frequently use other modifier keys globally (e.g. the Window/Apple/Mod4 key).

**Comment by trajanmcgill** [comment] 2023-09-22 20:25
> Version 2.0.1 on Thunderbird 115.2.2 on Windows 11.
> 
> Ctrl+Shift+M or Y or G behave like the previous version of repeating the previous action. The previous Shift+M or Y or G to specify new choices can only be done using the menu button instead of keyboard shortcuts. This would slow down the move. In case of limited choices, I would prefer using Ctrl-Shift+M or Y or G to bring up the new choice windows, which could include the last choice on the first row followed by other newly selected choices.

The reason Ctrl+Shift+M still works to repeat the previous action, and why it won't work here for a replacement for the old Shift-M, is that Ctrl+Shift+M is a _Thunderbird_ shortcut (not a shortcut belonging to this add-on) for repeating a move to the same folder. I've successfully configured Ctrl+Alt+M (and +C and +G) to work on Windows on the extension shortcuts config page, and they all seem to work. Haven't yet tried Linux but hoping it works there as well.

**Comment by unode** [comment] 2023-09-26 12:15
> Yeah, you can go into the shortcuts manager and assign your own. This, but in Thunderbird: https://support.mozilla.org/en-US/kb/manage-extension-shortcuts-firefox

I was able to set a different shortcut than the pre-configured one. The functionality I miss the most is "Move" so Ctrl+Shift+N, being unused, works. On my system Ctrl+Shift+M is a Thunderbird preset shortcut bound to "repeat last move" so I couldn't use it because it always triggered the 'repeat move" action.

Preset shortcuts (those that Thunderbird does natively) seem to take precedence over any shortcut set via extension. Makes finding an unused shortcuts for an extension rather difficult. I wonder if this is a bug in Thunderbird as, from the reported in this thread, the behavior is also inconsistent across operating systems.

The shortcut interface also seems rather limiting. For instance, it accepts Alt+Shift but then it behaves the same as Alt alone (the AltGr situation mentioned above?). Tried Alt+Shift+M but that just opens the Message menu. Again a preset shortcut taking precedence.
Shortcuts on Shift alone (e.g. Shift+M) are rejected or aren't allowed as the shortcut edit interface asks for an extra key (Alt or Ctrl).

But anyway, being able to edit the shortcut solved my issue. Even if this solution is not optimal and I need to get used to a different key combination.

**Comment by rigow** [comment] 2023-09-28 11:08
I changed all to CTRL+ALT on opensuse with KDE and everything works as expected. As soon as there are conflicts in shortcuts, strange things happen. Either it refuses to work or it does repeat the latest operation on the selected email. So IF the change is disruptive anyway and we are talking about 3 shortcuts that one uses several times a day, those should be changed to something that works. Because everybody will learn that quickly anyway.

**Comment by kewisch** [comment] 2023-10-01 21:37
Hey folks, can you try this version? When you upgrade from 2.0.1 you should be getting a special upgrade window that tells you about the current shortcuts and tries to explain the situation. Here is what to expect:
* The only shortcut that by default has a key assigned is move.
* Ctrl+Shift+N on Windows/Linux, MacCtrl+Shift+M on Mac.
* Other shortcuts are unassigned by default, but modes can either be reached using left/right arrows after opening the popup, or assigning your own shortcuts.

Is the text clear and understandable? Is anything not working with the new shortcuts?

[quick_folder_move-2.6.3.zip](https://github.com/kewisch/quickmove-extension/files/12778283/quick_folder_move-2.6.3.zip)

**Comment by KC-T** [comment] 2023-10-02 18:42
Unfortunately, Ctrl-Shift-N on Windows has been used by CardBook to create a new contact. CardBook seems to be the only choice to use Google contacts with ease.

Pressing "Quick Move" will bring up Move / Copy / Goto / Tag but pressing any of them will not bring up any entry box.

Note that a similar app "Move messages and yourself" is using Ctrl+Shift+Z and X and A.

**Comment by kewisch** [comment] 2023-10-02 18:44
I can't also take other extensions into account, I'd run out of shortcuts quickly. I think cardbook users can just change the shortcut.

When you say it will bring up the popup but not an entry box, can you screenshot this? Do you get any error console messages?

**Comment by kewisch** [comment] 2023-10-03 15:26
Hey folks, I'd appreciate if you could test and come back with feedback. I have a holiday today, so if we can clear this out I can bring this to release.

**Comment by trajanmcgill** [comment] 2023-10-03 16:12
Hi. Several responses:

- I, too, use CardBook, and suspect this is quite a very common add-on, so Ctrl-Shift-N does pose a conflict.
- However, I had already configured Ctrl-Alt-M instead, for moving messages.
- 2.6.3 showed an upgrade message that was reasonably clear, and showed the shortcuts I had already configured (installing it didn't wipe the customizations I had previously made).
- However, 2.6.3 doesn't show a search window at all. I can see the menu where I choose "Move", "Copy", or "Tag", but the search box and the dropdown below it where I choose a destination folder are completely missing now.

![image](https://github.com/kewisch/quickmove-extension/assets/4105703/c800b6fa-991b-460e-8fb4-f805956b8b36)

**Comment by trajanmcgill** [comment] 2023-10-03 16:48
I'm unfortunately not very familiar with Thunderbird extensions, so I'm not immediately seeing what's wrong (and the diff from the previous version is fairly significant, so looks like there was some refactoring done), but in my quick attempt at debugging I'm seeing a "loading failed" message for the module `baseitemlist.js`, which I imagine may in turn be the cause of this error which happens afterward:
```
Uncaught (in promise) TypeError: folderList.initItems is not a function
    load moz-extension://cad718d6-3ee0-46ee-9b0c-e1d39d01b41b/popup/popup.js:89
    async* moz-extension://cad718d6-3ee0-46ee-9b0c-e1d39d01b41b/popup/popup.js:150
```

**Comment by b3** [comment] 2023-10-06 08:55
> Hey folks, I'd appreciate if you could test and come back with feedback. I have a holiday today, so if we can clear this out I can bring this to release.

I just tested version 2.6.3 quoted in the [previous comment](https://github.com/kewisch/quickmove-extension/issues/88#issuecomment-1742209822) on my Debian bookworm's Thunderbird 115.3.1 version.

- when *Use classic shortcuts* is enabled it seems to work (well at least calls the extension),
- when it is not `Ctrl`+`Shift`+`M` still moves the message to an unknown folder (it seems to be the last one use to store a message through the extension but I am not sure about that.

The main problem is that with this version I am completely unable to move/copy/tag anything (nor with the keyboard shortcuts, nor with the mouse) since I do not have access to the search list at all, but I may have miss some important change in the UX.

**Comment by kewisch** [comment] 2023-10-06 09:35
> when it is not `Ctrl`+`Shift`+`M` still moves the message to an unknown folder (it seems to be the last one use to store a message through the extension but I am not sure about that.

You will not be able to use Ctrl+Shift+M. I cannot overwrite built-in commmands. The new version will deliberately default to Ctrl+Shift+N instead. Did a screen appear on upgrade to tell you about the new shortcuts? Feel free to share a screenshot, you should be able to get it back by upgrading again. 

I'm worried we are running into a situation where it will use Ctrl+Shift+M because of some back and forth between settings, if so I'd need to find a way to identify that situation and reset the command.

> The main problem is that with this version, and as @trajanmcgill stated in this [previous comment](https://github.com/kewisch/quickmove-extension/issues/88#issuecomment-1745300751), I am completely unable to move/copy/tag anything (nor with the keyboard shortcuts, nor with the mouse) since I do not have access to the search list at all, but I may have miss some important change in the UX.
Do you see a Quick Folder Move toolbar button in the main menu bar, or in the message header bar? 


> I am backtracking to the 2.0.1 version for now which seems to _work_ with old style shortcuts even if :
We'll get to 2.6.3 thanks to your testing and responses!

**Comment by b3** [comment] 2023-10-06 10:36
The warning screen appears correctly after installing the extension as seen in this screenshot (menu are in french since I use TB in french) : 

- ![Capture-du-2023-10-06-12-17-26](https://github.com/kewisch/quickmove-extension/assets/404828/f060c5fb-b986-4583-bdba-418c5c1a6d1f)
- ![Capture-du-2023-10-06-12-18-31](https://github.com/kewisch/quickmove-extension/assets/404828/35401c16-c67c-47d7-a5a3-944597c175a6)

I have a *Quick Folder Move* in the main toolbar (which, in a completely off-topic subject I got a lot of difficulties to [put at the *right natural* place](https://support.mozilla.org/en-US/questions/1422908) when upgrading to SuperNova) : 

![Capture-du-2023-10-06-12-18-57](https://github.com/kewisch/quickmove-extension/assets/404828/fac02215-dba2-48a3-9f5e-022ef6e9b616)

I did not get the the message @trajanmcgill get in the error console when starting TB as you can see in the attached file (containing only errors and warnings):

[console-export-2023-10-6_12-34-58.txt](https://github.com/kewisch/quickmove-extension/files/12829980/console-export-2023-10-6_12-34-58.txt)

**Comment by kewisch** [comment] 2023-10-06 11:32
Ah alright. The error messages don't seem to be related to this add-on. So you mentioned you can at least open the popup with Shift+M. Does it appear empty just like in @trajanmcgill 's screenshot? Do you have all of the boxes checked in the error console w.r.t showing messages? 
![image](https://github.com/kewisch/quickmove-extension/assets/607198/46693d90-93bd-4487-9617-0be949618b8f)

Can you try and disable conversations and cardbook to see if this affects the popup in any way?

**Comment by l8com** [comment] 2023-10-06 13:04
When using Ctrl-Shift-U I get the same that trajanmcgill had: [the three buttons appear but no target folder list](https://github.com/kewisch/quickmove-extension/issues/88#issuecomment-1745300751). 
The same with Ctrl-Shift-h. 
I am using Windows 11 (German), TB 115.3.1 (64 Bit, German) and Quickmove 2.6.3. 
'will go back to the release now...

**Comment by b3** [comment] 2023-10-06 13:33
OK. I now get a very strange behavior with the extension (no keyboard shortcuts are working anymore). I will start everything from scratch.

1. remove the extension completely
2. restart TB
3. download [2.6.3 extension](https://github.com/kewisch/quickmove-extension/files/12778283/quick_folder_move-2.6.3.zip)
4. start TB and install the extension from the zip file
5. I got the information message:
  - ![Capture-du-2023-10-06-15-10-02](https://github.com/kewisch/quickmove-extension/assets/404828/67944ab5-d105-453c-8bd7-72b5720dd0f9)
7. default behavior is to have *new* keyboard shortcuts as expected: 
  - ![Capture-du-2023-10-06-15-11-08](https://github.com/kewisch/quickmove-extension/assets/404828/9eafa227-9328-4861-bb5f-ef2c0b77a223)
  - ![Capture-du-2023-10-06-15-10-37](https://github.com/kewisch/quickmove-extension/assets/404828/70f6730b-0ffa-47c9-8892-eae1bbe5283d)
8. None of them are working
9. switching to classical ones install automatically the old ones
  - ![Capture-du-2023-10-06-15-11-56](https://github.com/kewisch/quickmove-extension/assets/404828/53800e42-4ca7-48ba-8eae-7f47f06faabe)
  - ![Capture-du-2023-10-06-15-16-26](https://github.com/kewisch/quickmove-extension/assets/404828/f67037b7-9087-48c4-bcc0-2b60a5d97a84)
11. using them starts the popup empty as in @trajanmcgill case:
  - ![Capture-du-2023-10-06-15-12-38](https://github.com/kewisch/quickmove-extension/assets/404828/9a8640af-599a-45f0-955f-d751c28e8a3c)
12. clicking the *Quick Move* button in the toolbar produces the same thing
   - ![Capture-du-2023-10-06-15-11-25](https://github.com/kewisch/quickmove-extension/assets/404828/61db58bc-03a4-45d5-afc6-368e6c3648a5)
13. disabling Cardbook (I do not use Conversations so I do not know how to disable it)
  - ![Capture-du-2023-10-06-15-25-32](https://github.com/kewisch/quickmove-extension/assets/404828/35f969f9-4d7d-4c4e-b5a2-4df6f22be3fd)
14. trying to use the extension does not seems to change anything (pop up window does not have the search space)
  -  ![Capture-du-2023-10-06-15-26-56](https://github.com/kewisch/quickmove-extension/assets/404828/3daf4428-ea31-4c03-a9a9-a8a5ba63bfdb)
15. checking all parts of the error console
  -  ![Capture-du-2023-10-06-15-28-12](https://github.com/kewisch/quickmove-extension/assets/404828/4d6e938d-b0f6-4bca-b507-36672435808c)
16. no messages seems related to the extension (but I am a TB code experts at all)
  - [console-export-2023-10-6_15-29-40.txt](https://github.com/kewisch/quickmove-extension/files/12831606/console-export-2023-10-6_15-29-40.txt)

**Comment by trajanmcgill** [comment] 2023-10-06 18:32
Ok, I've tried now on both Windows and Linux installations, with the same results. Working with Thunderbird 115.3.1 (64-bit). 

Steps:
1. Uninstall the release version
2. Restart TB
3. Install from the above ZIP file
4. Adjust shortcuts so they work in conjunction with CardBook (so I'm changing "Move" to be Ctrl+Alt+M)
5. Go to my inbox and hit either the shortcut key or the Quick Move button.
6. Result: I get the Move / Copy / Tag button popup, but it has no folder list or input text box for choosing a destination folder.

If I do the above with the dev tools console open, I get this:
![image](https://github.com/kewisch/quickmove-extension/assets/4105703/f1253ef2-0702-4db1-9018-7d30b39b18c7)

**Comment by kewisch** [comment] 2023-10-06 20:38
Ooooh there we go. Filenames are case insensitive on some mac filesystems :-) Try this one:

[quick_folder_move-2.6.4.zip](https://github.com/kewisch/quickmove-extension/files/12835332/quick_folder_move-2.6.4.zip)

**Comment by kewisch** [comment] 2023-10-06 22:04
And another version update. Changes:
* If there are no toolbar buttons to attach to, fall back to a window
* Fix finding the current account in message display windows

[quick_folder_move-2.6.5.zip](https://github.com/kewisch/quickmove-extension/files/12835691/quick_folder_move-2.6.5.zip)

**Comment by kewisch** [comment] 2023-10-06 22:53
Can someone with a non-english keyboard on Windows that regularly uses AltGr test and see what happens when you use `Ctrl+Alt+M`, `Ctrl+Alt+C` and `Ctrl+Alt+G`? I'm having second thoughts about Ctrl+Shift+N, it really bugs me that it is N not M. 

I'm actually hoping that the accented characters is not an issue, because the keyboard shortcuts should only trigger when not in a textbox. Aside from checking if the popup opens, maybe also go into some other textbox in the main window and type an accent that uses Ctrl+Alt or AltGr.

**Comment by kewisch** [comment] 2023-10-06 23:42
Here is a version that defaults to `Ctrl+Alt+[MCGT]`

[quick_folder_move-2.6.7.zip](https://github.com/kewisch/quickmove-extension/files/12836001/quick_folder_move-2.6.7.zip)

**Comment by trajanmcgill** [comment] 2023-10-07 03:23
Okay, have found the problem. Version 2.6.7 still doesn't work, but I am able to make it work with a quick fix. Also have realized that two issues have gotten mixed together in one issue's comment thread; apologies for that. Two notes on these things:

1. The cause of the missing file list issue, which as I said does persist in 2.6.7, is here:
![image](https://github.com/kewisch/quickmove-extension/assets/4105703/941a033d-861e-4d38-a0ca-b87d94b28138)
You can see that the file names are not capitalized the same way in each of those places. If I change the file name case to match the imports (or, presumably, the other way around), then re-zip the package, it then works perfectly. I just sent you a pull request with the file name change.

2. This is more directly connected to the original description for this issue. I personally prefer the new default keyboard shortcuts (which happen to be exactly what I chose myself), but the below screen now needs to be updated to match the changes you've made. It still claims only one shortcut is being set up and that it is Ctrl+Shift+N.
![image](https://github.com/kewisch/quickmove-extension/assets/4105703/7a68fe2d-4b49-4ef6-80fb-749e0dffc4ee)

**Comment by kewisch** [comment] 2023-10-07 11:54
Huh, I thought I took care of all the filenames, weird. Here is a fixed version for both issues:

[quick_folder_move-2.6.8.zip](https://github.com/kewisch/quickmove-extension/files/12837660/quick_folder_move-2.6.8.zip)

**Comment by kewisch** [comment] 2023-10-07 12:11
Could you also change your keyboard layout to something like Polish or German and play around with Ctrl+Alt+M/C/G/T to see if it works well?

**Comment by kewisch** [comment] 2023-10-07 18:20
Alright, no chance. I tested Ctrl+Alt+M on the ENG INTL layout and it just doesn't go through.

**Comment by kewisch** [comment] 2023-10-07 19:44
It feels like the never ending story. Now I thought maybe Ctrl+Period would be good because it works across all platforms and is just 2 keys. However, some keyboard layouts have the period on Shift, so on these layouts it will simply not work no matter if you use Shift or not. I can make it locale dependent, but I couldn't make it keyboard layout dependent.

Going back to Ctrl+Shift+N then, I don't think there is a good choice out there.

**Comment by kewisch** [comment] 2023-10-07 20:23
Alright, I'm going to consider this one done. Things should be working now, as best they can. If you see any other issues feel free to file a new issue.

I'm going to leave a day grace period and then push this out to release.

[quick_folder_move-2.6.9.zip](https://github.com/kewisch/quickmove-extension/files/12838862/quick_folder_move-2.6.9.zip)

**Closed by kewisch** 2023-10-07 20:23 UTC
Labels: bug

**Comment by b3** [comment] 2023-10-09 00:47
2.6.9 seems to work (at least the box appears) on my Linux (Debian Bookworm, TB 115.3.1). The new layout is however not working, I had to switch to *classical keyboard shortcuts* for it to work.

**Comment by kewisch** [comment] 2023-10-09 07:20
@b3 Interesting. What keys did it say you are using in the changes page that occurred on install? Do you have other add-ons such as Cardbook installed?

**Comment by kewisch** [comment] 2023-10-09 08:52
No, I cannot make Ctrl+Shift+M work, due to technical restrictions in Thunderbird. For me Alt+M did not work on WIndows since it opened the Message menu, but I'm glad it does for you!

**Comment by b3** [comment] 2023-10-10 14:56
Yes I have more extensions installed, and yes I use CardBook. You can see the list of my extension in one of the snapshot of [a previous comment](https://github.com/kewisch/quickmove-extension/issues/88#issuecomment-1750690656).

I am not sure to understand your first question though. Do you ask the key shown in the welcome message when installing the extension (as shown in the following screenshot).

![Capture-du-2023-10-10-16-55-22](https://github.com/kewisch/quickmove-extension/assets/404828/c924104b-a4e7-4c44-bab0-97f72abc1489)

**Comment by kewisch** [comment] 2023-10-10 15:15
Looking for this shot: 
![image](https://github.com/kewisch/quickmove-extension/assets/607198/26d50c40-daba-4832-bb3a-785d029f1b06)

If you use Cardbook, neither Ctrl+Shift+M nor Ctrl+Shift+N will work and you'll just have to pick one that works for you.

**Comment by kewisch** [comment] 2023-10-11 20:55
Yeah, some of these add-ons are using the legacy extensions architecture to define their keyboard shortcuts, so they won't show up in the shortcuts manager. I can understand how this is super confusing without all of this behind-the-scenes information!

**Comment by KC-T** [comment] 2023-10-12 06:31
I would like to remind that Control-Shift-M is used by Thunderbird 115 to move selected messages to move-destination folder previously used by Thunderbird itself, not the folder previously used by Quick Move. However, I have not tested the latest Quick Move to see whether Quick Move can override that destination.

**Comment by kewisch** [comment] 2023-10-12 20:03
Indeed, good reminder given the issue has gotten lengthy. The new version (which should now be released!) defaults to Ctrl+Shift+N (N, not M) on windows and linux. If you are seeing anything different please do feel free to file a new issue.

Quick Folder Move cannot override the keyboard shortcut using the more stable extensions APIs.

**Comment by KC-T** [comment] 2023-10-12 21:53
Ctrl-Shift-N opens a new contact under CardBook. I cannot find any descriptions about CardBook regarding setting or re-setting keyboard shortcut there.

I now use Alt-B for move, Alt-C for copy and Alt-D for GoTo under Windows 11. They work fine. Ctrl-Shift-M as provided by Thunderbird can repeat moving to destination folder previously used by Quick Move. Seems all good.

I would like to thank you for resolving the keyboard problem.

Now I would like to say that I would prefer the previous style of listing the selected folders where the parent folder names are given on the left instead of on the right because I can then quickly lookup the correct parent folder and choose the relevant item. I have many sub-folders of the same name under many different parent folders.

**Comment by b3** [comment] 2023-10-13 01:24
So do I, but this is a question of taste and since the information is still there I guess I will survive ;-)
