### ISSUE TITLE
Move entire conversation

### ISSUE THREAD

**Issue by jojobabrian** [kewisch/quickmove-extension#168] opened 2024-08-27 19:08 UTC
Before this last upgrade (I believe), when you Quickmoved a collapsed  conversation, the whole conversation was moved to the selected folder. Now only the "top" message is moved, so you have to make multiple moves, which is not very... quick.  If you expand the conversation and select all the messages, they will all move. 

Thank you for the great extension. Saves me tons of time.

**Comment by unode** [comment] 2024-09-06 18:31
Seeing the same behavior here:
- Thunderbird - 128.1.1esr (Linux)
- Quick Folder Move - 2.9.2

**Comment by dharabor** [comment] 2024-09-10 09:23
I just wanted to chime in and say that my experience is similar to previous commenters. The addon (which is great usually -- thank you!) has been completely broken for some weeks.

Thunderbird 128.01esr (Linux)
Quick Folder Move 2.9.2

**Comment by sciancio** [comment] 2024-09-10 10:29
Same behavior on my installation.

Thunderbird thunderbird-128.2.0-1.fc40.x86_64 (Fedora/Linux)
Quick Folder Move 2.9.2

**Comment by kewisch** [comment] 2024-09-11 05:59
The expected behavior is that the whole conversation is moved. I'm using the standard API to get selected messages, worst case we'll need to get some changes into Thunderbird to allow returning the whole conversation when collapsed.

This is an "easy" thing for someone to investigate that feels comfortable using the debugger, finding out what the API result is, and if there is a way to get the API to return all relevant messages.

**Comment by unode** [comment] 2024-09-16 19:26
Inspected with the debugger and this looks like an UI/API upstream bug.
Meanwhile found that someone [already opened bug 1918885](https://bugzilla.mozilla.org/show_bug.cgi?id=1918885).

Wasn't able to find a combination of API calls fit for a workaround.
Looked for a way to retrieve collapsed/threaded information so as to find which other messages are being collapsed but no luck.

Seems like we may need to wait for an upstream fix.

**Comment by unode** [comment] 2024-09-16 19:32
Meanwhile I noticed that if one uses the *Move to* menu option (top-right corner of the collapsed message - 3 dots menu), all messages are moved.
Same for the *Move again* option.

**Comment by dharabor** [comment] 2024-09-17 07:34
I found a "Move to" option in the right-click (on a message) menu options but it did not seem to move the whole thread. Dragging the thread to the folder works, but of course is not very quick. Could the plugin use whatever feature/function the dragging action uses/calls? Might be a better option than waiting for an upstream fix.

**Comment by gvlx** [comment] 2024-09-17 17:52
This is what I found, when moving the messages in the collapsed topic (three times - repetitions marked «»):

```
18:47:50.484 Promise rejected after context unloaded: Actor 'Conduits' destroyed before query 'RuntimeMessage' was resolved
«3» popup.js:162
    unload moz-extension://55b9489d-1f8e-4a0e-aaea-ae2a1fca0cf7/popup/popup.js:162

18:48:14.979 Unknown property ‘pad-right’.  Declaration dropped. «2» fetch>UID>.INBOX>24787:1:51

```

**Comment by kewisch** [comment] 2024-09-17 21:02
> Inspected with the debugger and this looks like an UI/API upstream bug.
> Meanwhile found that someone [already opened bug 1918885](https://bugzilla.mozilla.org/show_bug.cgi?id=1918885).

Yes, thank you for linking the bug. I pinged the team in the add-on developers channel about this and indeed the behavior changed unexpectedly. The API will likely be changed to accommodate both choices, and I hope the default ends up being to return all messages in the conversation, which would fix this bug automatically.

**Comment by gordol1** [comment] 2024-09-21 00:15
> Before this last upgrade (I believe), when you Quickmoved a collapsed conversation, the whole conversation was moved to the selected folder. Now only the "top" message is moved, so you have to make multiple moves, which is not very... quick. If you expand the conversation and select all the messages, they will all move.
> 
> Thank you for the great extension. Saves me tons of time.

Same here. Currently running v2.9.2 in TBird 128.20esr 64bit in Windows 11 Home (two machines) and Win10 Home (one machine). However this predates my upgrade to Nebula, it also was happening in TBird Supernova 115.

**Comment by kewisch** [comment] 2024-09-21 06:23
John from Thunderbird is working on this issue, it will likely be fixed in the next point release or two. I'll leave this issue open until this has happened.

**Comment by gordol1** [comment] 2024-09-21 13:54
> John from Thunderbird is working on this issue, it will likely be fixed in the next point release or two. I'll leave this issue open until this has happened.

Thank you.

**Comment by kewisch** [comment] 2024-11-21 20:43
I've tested this on beta and it works as expected. For the sake of cleaning up I'm going to close the issue now. Thank you everyone for your help, and John for fixing the issue!

**Closed by kewisch** 2024-11-21 20:43 UTC
Labels: bug, upstream

**Comment by jojobabrian** [comment] 2024-11-22 10:33
Thank you @kewisch and everyone for your work on this. 

Now to unlearn the muscle memory of using the right arrow key and shift-down arrow key to select all the messages before Quickmoving them. :)
